spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Komis
    username: postgres
    password: student
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # utworzy tabele
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl.import_files: import.sql
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.schema.internal.script.SingleLineSqlScriptExtractor
  sql:
    init:
      mode: never  # WYŁĄCZ import.sql

server:
  port: 8080